### ISSUE TITLE
version of extra headers schema

### ISSUE THREAD

**Issue by crotwell** [iris-edu/miniSEED3#10]
Currently the json-schema for the extra headers is unversioned. As it is anticipated that the FDSN can update this by adding to the "reserved" section of the extra headers, this schema should be versioned, if only to allow verification that any change is backwards compatible.

**Comment by chad-earthscope** [comment]
+1 to version the schema itself.

Do you _also_ suggest including a version in an instance document?

**Comment by crotwell** [comment]
I guess a reference to the schema version in an instance is possible, but if the intent is that the FDSN section of the  extra headers should only change in backwards compatible ways, eg adding new keys, then maybe is isn't needed?

Given also that in most cases the extra headers will be small, seems less desirable to require the additional bytes for a schema version for something that is pretty simple. 

Perhaps some verbiage to the effect that extra headers with no schema version are assumed to be 1.x compatible, and  then we need only create a "schema version" extra header if it becomes necessary for a 2.0 schema? Not sure about this to be honest, but well worth thinking about before rather than later.

**Comment by crotwell** [comment]
@chad-iris can you rename [ExtraHeaders-FDSN.schema.json](https://github.com/iris-edu/miniSEED3/blob/main/extra-headers/ExtraHeaders-FDSN.schema.json) to include a version,
perhaps 
`ExtraHeaders-FDSN_v1.schema.json` or perhaps `ExtraHeaders-FDSN_v2022.schema.json`?

**Comment by chad-earthscope** [comment]
I went with `ExtraHeaders-FDSN-v1.0.schema.json` to give us a little more room for noting incremental changes and a future, incompatible v2.
