### ISSUE TITLE
add fdsn standard extra header keys for stationxml and quakml

### ISSUE THREAD

**Issue by crotwell** [iris-edu/miniSEED3#12]
While not useful in most cases for data centers, it is often useful in research to associate an event with a time series within a single file. For example, the sac file format has headers for event latitude, longitude and depth. Because these are standard, tools can easily find and use them. Putting channel metadata into the record, while perhaps space-inefficient, is also often useful.

While we could create specialized json objects to store this type of information, we already have the QuakeML and StationXML XML formats, which are just of course just strings. 

Propose that we reserve keys within the fdsn portion of the json extra headers for QuakeML and StationXML. The idea is that one could insert the contents of a QuakeML or StationXML file as a string into the json extra headers, allowing this metadata to be contained within a mseed record. Because these two file formats (actually string formats) are already standardized, tools should already know how to deal with them and so the standard key is all that is needed. 

Optionally, these could also be stored in otherwise "empty" records, eg no time series data, allowing one copy within a mseed3 file that might have many records. The association here would be to other records in the file, but would still provide a simple and useful way to aggregate related information in a standard way.

Suggest adding to the json schema:
```
                "QuakeML": {
                    "description": "QuakeML XML as a string",
                    "type": "string"
                },
                "StationXML": {
                    "description": "StationXML XML as a string",
                    "type": "string"
                },
```

And yes I do realize it is weird to have one file format (mseed3) containing another file format (json) which then contains yet another file format (XML).

**Comment by djeastonca** [comment]
I recognize that associating metadata with data is a problem for which we currently depend on a overarching system to resolve (i.e. the means to ask a data center service for the corresponding metadata for a given time range or, more primitively at the other end of the spectrum, association of files in the filesystem when data is harvested directly from a datalogger). However I'm not sure that inviting metadata to be stored directly into the mseed record is the best approach to improve on this as it leads to storage inefficiency and duplication along with potential ambiguity around the location of the 'single source of truth' of metadata.

**Comment by crotwell** [comment]
I think the question isn't whether or not users will do this type of thing, the question is will they do it in a single standardized way or not. The worst outcome imho is everyone putting the same information into the extra headers in different, incompatible ways. 

I am actually currently working on a tiny little coding project where I need to have a single file that contains the timeseries, station location, event location and a user's time picks. Sure, I could use a zip file as a wrapper with mseed3, stationxml and quakeml files inside, but that means that other tools that know about mseed3 will not be able to use my output directly. So, I will be putting some kind of metadata/event info into the mseed3 files. Without a standard key, I will be forced to just make up my own way of doing it, and that seems unfortunate. 

Again, I do not think this is a good idea for distribution from data centers, the single source of truth and the data duplication problems are totally valid in that case. However, once the mseed has landed on a researcher's disk, requiring a metadata management system or even just a specific directory structure just to have the event lat/lon and depth available puts up an energy barrier to adoption. The sac file format, even given its age and limitations, is still widely used in research, and I would argue that the ability to include metadata and event info in a single file is a big part of the reason why. Mseed3, with it more flexible extra headers, I think could really become the best research format in addition to the best distribution format if it could do this too.

A simplier json object may be a better alternative to full stationxml and quakeml, but using these exiting formats and only specifying these two keys seemed the least complicated, least invasive method to me.

**Comment by djeastonca** [comment]
Fair enough - you're pointing out that it's going to happen regardless in a use case that I'm not considering. So your proposal makes sense under the premise that this is a common use case that would therefore benefit from such encapsulation.

**Comment by chad-earthscope** [comment]
It might be worth exploring if such a mechanism could be more general: for example a reference in the extra headers (ala JSON-LD or some sort of JSON pointer) that could then be used to indicate a URL (could be a file adjacent to the data), that contains related information with a type declaration (e.g. StationXML, QuakeML).  This would allow such a reference to be usable with future data formats.  It does require other files though and so some sort of container (e.g. ZIP) for packaging, but this could be a good thing where multiple records could refer to the same StationXML file that describes multiple channels with common network and station details.

No, I do not have any schema ideas for this.  I'm concerned that the StationXML and QuakeML-specific embedded entries are very limiting, and trying to figure a way to handle the use case in a more general way.

**Comment by crotwell** [comment]
Totally fine with an any alternatives, but I am not sure I see the point of a reference to a separate file that then requires yet another container. If we are going to do that, you could just have a zip file with a standard directory structure and filenames for the StationXML and QuakeML. The FDSN probably isn't going to approve a large number of additional standard data formats, so I am not sure I see why they need to be part of a general linking scheme.

I would actually prefer a solution that allowed basic info as straight JSON in the extra header. Maybe we could create a simple object for basic earthquake and station info? But everything in QuakeML or StationXML is potentially useful to somebody, so I worry that this would grow to effectively be a JSON version of QuakeML and StationXML. Not that that would be a bad thing, but seems like a lot of work compared to just allocating 2 keys.

**Comment by djeastonca** [comment]
@crotwell I agree with your point about how the notion of a simple object would be a very slipperly slope towards embedding full QuakeML or StationXML. However I'm not clear on why there may be resistance in the FDSN to the notion of defining a data format used for the packaging of data and metadata for portability. To me this seems to be the analogy of why the Java jar format was created. 

Also, per @chad-iris 's earlier point about referencing, one could imagine that the metadata in this package could also include a reference to the root metadata in the source archive (e.g. IRIS DMC). This would also address my earlier concern about duplication and the risk of losing the reference to the 'ultimate source of truth' for the associated metadata.

**Comment by crotwell** [comment]
While I still think some form of station and earthquake information in the extra headers is a good idea, I don't think it is important enough to hold up the approval process, and so why don't we close this issue as won't fix. 

Also after some talking with @chad-iris I have come around to the idea that maybe it would be better as a "de facto" standard that exists outside of the "fdsn" namespace in the extra headers, and so does not need to be part of the spec. I will work on something and post to the larger working group list under the "Guidelines for Extension" part of the mseed3 spec after this work is done. The greater flexibility is probably good and a de facto standard may be every bit as useful in the long term as an officially adopted standard.
