### ISSUE TITLE
extra headers schema link broken

### ISSUE THREAD

**Issue by crotwell** [iris-edu/miniSEED3#14]
The link to the json schema file for the extra headers is broken. I know this will change upon transfer to fdsn, but would be nice to have it correct during review.

https://miniseed3.readthedocs.io/en/latest/extra-headers.html#fdsn-reserved-headers

@chad-iris can you fix this easily?

**Comment by chad-earthscope** [comment]
Kinda an oddity.  That link was to the GitHub Pages render of the docs, which are a partial rendering of what we are now putting into readthedocs.org and I believe confusing should anyone stumble on them.  

I'll replace it with a link to the raw repository file, which _is_ the canonical version.

**Comment by chad-earthscope** [comment]
Viewable in the draft render for now:
https://miniseed3.readthedocs.io/en/draft/extra-headers.html
