### ISSUE TITLE
URI scheme registration

### ISSUE THREAD

**Issue by djeastonca** [iris-edu/miniSEED3#16]
Pending the resolution to issue #15 , should it be or has it been considered to register the FDSN URI scheme with [IANA](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml)?

**Comment by crotwell** [comment]
Seems a reasonable thing to do, although I am not sure of how much practical value there would be. Is there anything you know of that would be an advantage, other than having an entry in that table?

**Comment by djeastonca** [comment]
I don't have a concrete benefit to cite, but it just seemed right to treat the scheme as a first class thing since it will be used across the world for decades to come. However the strength of that argument becomes diminished with the departure from syntax convention.
