### ISSUE TITLE
formating of times in reference data

### ISSUE THREAD

**Issue by crotwell** [iris-edu/miniSEED3#18]
Times in reference data are inconsistent.
For example in reference-detectiononly.txt:
```
             start time: 2004,210,20:28:09.000000
```
while in same file
```
                        "OnsetTime": "2022-06-05T20:32:39.120000Z",
```
which are slightly different. First has day of year, second month-day. First doesn't have `Z` for UTC.

Also, mseed3 has nanosec precision, but both times are microsecond.

JSON version of same file has 
```
    "StartTime": "2004-07-28T20:28:09.000000000Z",
```
which is again slightly different, nanosecond with `Z`, and month-day. The JSON also has
```
                        "OnsetTime": "2022-06-05T20:32:39.120000Z",
```
with only microsec precision.

Would be nice if all of these were unified. While I like the month-day format in general, the mseed3 format has day of year, so that might be a more accurate representation?

**Comment by crotwell** [comment]
Realized that the extra-header times are just text, so their format reflects the mseed2-3 conversion, so maybe out of scope. 

ISO8601 has a year-dayofyear format, and so even when using day of year in the text output, it could still be a standard format. Recommend change
```
             start time: 2004,210,20:28:09.000000
```
to
```
             start time: 2004-210T20:28:09.000000000Z
```
in the text output. This format might also be best for the json output as well.

Related issue https://github.com/iris-edu/mseed3-utils/issues/24

**Comment by chad-earthscope** [comment]
These time formats are now in the preferred and recognizable [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339) format with an addition of the day-of-year value.
