### ISSUE TITLE
bit flags reversed in text output

### ISSUE THREAD

**Issue by crotwell** [iris-edu/miniSEED3#19]
See https://github.com/iris-edu/mseed3-utils/issues/25

Bit flags in text version of reference data has wrong order.
```
                  flags: [00100000] 8 bits
                         [Bit 2] Clock locked
```
but clock locked should be third bit from right, not left, so should be
```
                  flags: [00000100] 8 bits
                         [Bit 2] Clock locked
```

**Comment by chad-earthscope** [comment]
Agreed, it should change to what you suggest: most-significant bit first (MSB-first).  This least-significant bit first convention was adopted from past software by libmseed, and, while it will be a change of libmseed's output, I do not believe it will be disruptive for most uses, and, if it will change this is the best time.

https://github.com/iris-edu/libmseed/issues/83
