### ISSUE TITLE
expression of the sampling rate (header field 6)

### ISSUE THREAD

**Issue by kaestli** [iris-edu/miniSEED3#7]
We would actually prefer a representation of the sampling rate by two integers (numerator, denominator)

Reasoning:
At least as long as the sampling rate is rational (afaik, we have not met others), this representation is more precise  and less prone to code implementation issues and equality check mismatches due to slightly different floating point representation of the same sampling rate, depending on platform, code and compiler versions.
It would probably be good enough to use 4 bytes integers for both numerator and denominator, leaving the header size unchanged.

**Comment by crotwell** [comment]
I do not have strong feelings here, but the original rationale was to handle the case of long baseline time corrections, for example OBS. To take an extreme example, a one year OBS deployment at microsecond precision overflows a 32 bit integer. Equality is also challenging with a numerator/denominator system as there are multiple equivalent representations, ie 2/200 is the same as 1/100 which is almost the same as 9999999/1000000000. I feel that in most cases equality of actual sample rate is rarely needed, being within a tolerance is sufficient.

And as a practical matter, any processing system must convert the two numbers into a floating point value to do math anyway, so it might as well be stored that way. 

The use of positive means sample rate and negative means sample period was designed to help with ease of representation for both very long and very short period data.

Important to note that this field is actual sample rate, ie blockette 100 field 3 in miniseed2. The nominal sample rate, which usually is a simple rational, should be recovered from the stationxml metadata.

**Comment by chad-earthscope** [comment]
Note that the decision on format requirements stated a value of "double precision/64 bit":
https://github.com/FDSN/miniSEED3-TechnicalEvaluation/blob/master/report.md#requirement-provide-support-for-high-sampling-rates

P.S. the sample period notation using a negative value is useful for more accurate representation of many sub-second rate values.  For example, a rate of 0.1 sps is not precisely represented in a float, but using -10 [edit] it is represented exactly.

**Comment by crotwell** [comment]
Just to be picky and for future reference, 0.1 sps => -10 as negative period. Otherwise agree.

**Comment by chad-earthscope** [comment]
Regarding the OBS support, here is Wayne Crawford's comment from the discussion in 2017:
https://github.com/iris-edu/mseed3-evaluation/issues/29#issuecomment-325934930

**Comment by chad-earthscope** [comment]
Closed at the request of the review group.
