### ISSUE TITLE
Suggestion: "Length of data payload" field should explicitly state that padding is allowed

### ISSUE THREAD

**Issue by luca-s** [iris-edu/miniSEED3#9]
In the description  of "Length of data payload" field, it would be useful to clearly state that padding is allowed. It that wasn't the case the field would be redundant, since the number of samples and encoding information would be enough to know the payload length.

**Comment by crotwell** [comment]
Unfortunately this is not true for encoding that do compression, for example the steim1 and steim2. Since the number of bits per sample varies within the record, there is no easy way to calculate the payload length.

The intent, I believe, is that padding should be avoided except where required by the encoding, ie steim1 and 2 require 64 byte frames.

**Comment by luca-s** [comment]
I understand, so the "Length of data payload" field is there to figure out right away the full length of the packet in case the compression is used. However in both cases, compression and non-compression, the reader of the miniSEED will know how many bytes to read (when there is no compression it is trivial to compute and in the compression case the number of byes will be known at the end of decompression phase) and if that number of bytes differs from the value reported in the "Length of data payload" field the current standard doesn't say if the miniSEED should be considered valid or not. My suggestion is to clearly state that the miniSEED is valid and that the potential extra bytes could be considered padding and safely discarded.

**Comment by crotwell** [comment]
+1 on clarifying this situation in the docs, but I would recommend "pad only where required by the compression encoding." In the case where the payload length is not the same as calculated by the encoding and number of samples, I would consider the record invalid, or at least very suspicious.

Unlike miniseed2, the new spec does not use fixed record sizes, and so padding is no longer needed or useful.

**Comment by chad-earthscope** [comment]
> +1 on clarifying this situation in the docs, but I would recommend "pad only where required by the compression encoding."

In those cases the padding is a feature of the encoding and therefore payload, and not something that needs to be addressed by the record definition.  I'd rather clarify that "no padding is allowed" in the record, which should treat the payload opaquely and avoid defining rules about payload construction.

Edit: changed "packet" to "record", too much SeedLink on the brain...

**Comment by crotwell** [comment]
👍 
So perhaps the document should address the fact that the documentation of the record should not address the contents of the payload? How is that for convoluted reasoning!

**Comment by chad-earthscope** [comment]
Fixed in #24
